### ISSUE TITLE
v0.5.0 tracking issue

### ISSUE THREAD

**Issue by resir014** [kata-ai/kata-kit#21]
This issue is dedicated as an umbrella issue to track all the progress in kata-kit v0.5.0. Once all milestone items are completed, we can close this.

## TODO Items

- [x] Break up components into separate packages. (#17) - @resir014
- [x] Set up styled-components for styling. (#18) - @resir014
- [x] Port all components to v0.5.0. (#23) - @resir014
- [x] Remove bootstrap dependency (#20) - @resir014
- [x] v0.5.0 docs + Kata Design System (KDS) page. (#22) - @resir014 (sama mas Tri juga)
- [x] Additional components? - @resir014
  - [x] ~~`@kata-kit/marker` - Marker (#25)~~
  - [x] `@kata-kit/form` - Form fields

## Prepublish tasks

- [x] Upgrade dependencies
